server:
  port: 8080
graphql:
  spqr:
    http:
      enabled: true
      endpoint: /api/graphql
    gui:
      enabled: true
      endpoint: /api/graphiql
output:
  path:
    logging:
      user: data/transaction_logs_user.txt
    data:
      user: data/database_user.txt
logging:
  level:
    ru.bmstu.labs: trace